---
- hosts: myserver
  remote_user: root

  tasks:
    # update system
    - apt: update_cache=yes
    - apt: upgrade=full

    # enable firewall and fail2ban
    # todo: improve https://github.com/phred/5minbootstrap/blob/master/bootstrap.yml
    - name: install fail2ban
      apt: name=fail2ban state=present
    - name: activate firewall (only 22 and 80)
      ufw: state=enabled policy=reject
      ufw: rule=allow port=22
      ufw: rule=allow port=80

    # install and configure webapp
    - name: install git
      apt: name=git-core state=present
    - name: create project directory
      file: path=/opt/project state=directory
    - name: checkout project source
      git: repo=git@github.com:sspross/docker-django-fullstack.git dest=/opt/project accept_hostkey=yes

    # install docker and docker-compose
    # todo: use newest docker compose version, not fixed
    # todo: don't use unstable docker. but stable uses still fig atm.
    - apt_repository: repo='ppa:docker-maint/testing' state=present
    - apt: update_cache=yes
    - apt: name=docker.io state=present
    - name: install docker-compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.1.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    - file: path=/usr/local/bin/docker-compose mode="a+x"

    # install supervisor
    - apt: name=supervisor state=present
    - file: path=/var/log/webapps/ state=directory
    - name: create supervisor configuration
      template: src=config/supervisord.conf dest=/etc/supervisor/conf.d/webapp.conf
      notify: reread supervisord

  handlers:
    - name: reread supervisord
      shell: supervisorctl reread && supervisorctl update

