db:
  image: postgres

redis:
  image: redis

rabbitmq:
  image: tutum/rabbitmq
  environment:
    - RABBITMQ_PASS=mypass

django:
  build: .
  command: /bin/sh run.sh
  volumes:
    - /code/
    - webapp/:/code/
  environment:
    - DEBUG=True
    - DJANGO_SETTINGS_MODULE=webapp.settings.default
    - HTTPS=off
    - SECRET_KEY=asfasfasfasdfasdfsadfsadfasdfasafasd
    - VIRTUAL_HOST=dockerhost
  expose:
    - '8000'
  links:
    - db:db
    - redis:redis
    - rabbitmq:rabbitmq

worker:
  build: .
  command: su -m myuser -c "celery -A webapp worker -l info -Ofair"
  volumes_from:
    - django
  environment:
    - DEBUG=False
    - DJANGO_SETTINGS_MODULE=webapp.settings.default
    - SECRET_KEY=asfasfasfasdfasdfsadfsadfasdfasafasd
  links:
    - db:db
    - redis:redis
    - rabbitmq:rabbitmq

nginx:
  image: jwilder/nginx-proxy
  volumes_from:
    - django
  volumes:
    - /code/vhost.d:/etc/nginx/vhost.d:ro
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - '80:80'
    # - '443:443'
  links:
    - django:django
